config/routes.rb
Road03::Application.routes.draw do
  resources :employees

  get "pages/home"

  get "pages/contact"

  get "pages/whatWeDo"

  get "pages/whoWeAre"
  
  get "pages/home2"

end

app/models/employee.rb
# == Schema Information
# Schema version: 20110516030436
#
# Table name: employees
#
#  id                    :integer         not null, primary key
#  name                  :string(255)
#  intro                 :text
#  content               :text
#  contact               :text
#  quote                 :text
#  created_at            :datetime
#  updated_at            :datetime
#  smallPic_file_name    :string(255)
#  smallPic_content_type :string(255)
#  smallPic_file_size    :integer
#

class Employee < ActiveRecord::Base
  
  has_attached_file :smallPic,
       :styles => {
         :thumb=> "90x90#",
         :small  => "180x180#" }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.xml
  def index
    @employees = Employee.all
    @table_rows = (@employees.count * 0.5).to_i


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.xml
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.xml
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.xml
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to(@employee, :notice => 'Employee was successfully created.') }
        format.xml  { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.xml
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to(@employee, :notice => 'Employee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.xml
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to(employees_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def whatWeDo
  end

  def whoWeAre
  end

  def home2
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def random_employees_array
    
    @emp_array = []
    (0..(@table_rows*3-@employees.count-1)).each do |place|
      @emp_array[place]= "empty"
    end
    @employees.each do |emp|
      @emp_array << emp
    end
    @random_emp_array = @emp_array.sort_by{rand}
  end
  
  
private
  def find_slot
    @row = @emp_array.sort_by{rand}.first
    @slot = (0..2).sort_by{rand}.first
    find_slot unless @emp_array[@row]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_employee_index_display.html.erb
	<% this_array = random_employees_array %>
	<% (0..@table_rows-1).each do |row| %>
	  <% (0..2).each do |cell| %>
		<% employee = this_array[row*3+cell] %>
		<% if employee and employee != "empty" %>
		  <% link_to(employee) do %>
            <div class = "index_box">
			  <div class= 'index_name'><p><%= employee.name %></p></div>
			  <div class = "index_pic"><%= image_tag employee.smallPic.url(:small), :size => "180x180" %></div>
            </div>
          
  		  <% end %>
		
		<% else %>
	  	  <div class = "index_box">
			<div class = "index_pic"><%= image_tag "spacer.gif", :size => "180x180" %></div>
          </div>
		<% end %>
	  <% end %>	
	  <div class = "index_row"></div>
	<% end %>
</table>

app/views/employees/_form.html.erb
<%= form_for(@employee, :html => { :multipart => true }) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Role %><br />
    <%= f.text_area :intro, :rows => 2  %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_area :contact, :rows => 2 %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_area :quote , :rows => 2 %>
  </div>
  <div class = "field">
  	<%= f.file_field :smallPic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class = "admin">

<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<div class="admin">

  <%= render "employee_index_display" %>
	



	
	<p class = "para_with_headroom">
		<%= link_to 'New Employee', new_employee_path %>
		
	</p>
	
	
	
</div>

app/views/employees/new.html.erb
<div class = "admin">
	<h1>New employee</h1>

	<%= render 'form' %>

	<%= link_to 'Back', employees_path %>
	
</div>

app/views/employees/show.html.erb
<div class = "admin">
  <p id="notice"><%= notice %></p>
  <div class = "show_employee">
	<h3>
	  <%= @employee.name %>
	</h3>

	<p class = "bold ital">
	  <%= @employee.intro %>
	</p>
	
	<%= simple_format( @employee.content) %>

    <% unless @employee.contact.empty? %>
	  <p class = "ital">
	    <span class = "bold">e:</span>
	    <%= @employee.contact %>
	  </p>
	<% end %>
    <% unless @employee.quote.empty? %>
	  <p id = "employee_quote">
	    "<%= @employee.quote %>"
	  </p>
	<% end %>
	<% if @employee.smallPic.exists? then %>
		<%= image_tag @employee.smallPic.url(:small), :class => "show_employee_pic" %>
	<% end %>

    <p>
      	<%= link_to 'Edit', edit_employee_path(@employee) %> |
		<%= link_to 'Back', employees_path %>
		
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Road03</title>
  <%= stylesheet_link_tag :all %>
  <link href='http://fonts.googleapis.com/css?family=Quattrocento' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:bold' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Wire+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag :defaults%>
  <%= javascript_include_tag 'jquery.min', 'scripts'%>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div id = "container">	
  <div id = "col1wrap">
    <div id = "col1">	
    </div>
	<div class = "menuItem" id = "col1a"></div>
	<div class = "menuItem" id = "col1b"></div>
	<div class = "menuItem" id = "col1c"></div>
	<div class = "menuItem" id = "col1d"></div>
  </div>
  
  <div id = "col2">
  	<h2>What we do</h2>
    <p>2R is a strategy and innovation firm — with a big difference.</p>
    <p>Everything we do is about unlocking and empowering imagination and intelligence within organizations.</p>
    <p>We are unashamedly working to enable organizations not only to be smarter — but more human. We work with clients, not for them.</p>
		

	
    
  </div>
<div id = "col3">
  	<h2>What we do</h2>
  </div>
  <div id = "col4">
	<ul>
		<li id = "menuWhatWeDo" class = "menuItem">What we do</li>
		<li class = "menuItem">Who we are</li>
		<li class = "menuItem">What's new</li>
		<li class = "menuItem">Contact us</li>
	</ul>

  </div>
  <div id = "col5">
  	<h2>What we do</h2>
  </div>
</div>

app/views/pages/home2.html.erb
<div id = "home2">
  <div id = "container">
  	<div id = "headline">
	  <h1>strategy + innovation</h1>
  	</div>
	<div id = "lead" class = "domain">
	  <h2>lead</h2>
	</div>
	<div id = "strat" class = "domain">
	  <h2>strategize</h2>
	</div>
	<div id = "innov" class = "domain">
	  <h2>innovate</h2>
	</div>
	<div id = "engage" class = "domain">
	  <h2>engage</h2>
	</div>
	<div id = "clarify" class = "domain">
	  <h2>clarify</h2>
	</div>
	<div id = "learn" class = "domain">
	  <h2>learn</h2>
	</div>
	
	
	<div class = "dom_text" id = "lead_text">
		Leaders face uncertainty and the unknown. They take on the responsibility of equipping individuals and organisations with the will to make things 
		different and to realize potential. Designing genuinely better futures requires depth - the mindset and skill to lead with wisdom:

		    understanding how language shapes reality
		    revitalising and sustaining core conversations
		    framing compelling arguments for change
		    inspiring confidence and courage to co-design.

		We have used the power of language, conversation and presence to help leaders:

		    Lead from their own strengths
		    Draw our the brilliance in their teams
		    Frame compelling arguments
		    Face complexity and chaos
		    Engage their people in co-design.

		
	</div>
	
	<div class = "dom_text" id = "strat_text">
		A successful strategy is a robust blend of imagination and coherent intent, a dynamic fit of meaning and context. We work with clients to ignite their inherent creativity and  
		to design their future success by:

		    revitalising and harnessing imagination
		    redefining the industry landscape
		    recalibrating enterprise systems
		    re-energizing revenue models
		    reinvigorating legacy products and services.

		We have used the power of story, conversation and design to help leaders:

		    Rethink their industries and build new pathways into the future
		    Change deeply bureaucratic systems to become more relevant to customers
		    Create compelling value propositions that translate into competitive advantage.

		
	</div>
	<div class = "dom_text" id = "innov_text">
		Brilliant ideas that deliver a competitive edge come from a mindset and process of design. Second Road works with clients to:

		    create exceptional experiences for customers and employees
		    discover new, unmet customer needs
		    embed a creative disposition into the firm’s culture.

		We have used the power of imagination, design and innovation to help leaders:

		    Build a culture of creativity
		    Bring the user experience to life
		    Capture and create new customer value.


		
	</div>


  </div>	
</div>

app/views/pages/whatWeDo.html.erb
<h1>Pages#whatWeDo</h1>
<p>Find me in app/views/pages/whatWeDo.html.erb</p>

app/views/pages/whoWeAre.html.erb
<h1>Pages#whoWeAre</h1>
<p>Find me in app/views/pages/whoWeAre.html.erb</p>